services:
  hispd:
    build: .
    container_name: hispd
    environment:
      HISP_DB_IP: mariadb
      HISP_DB_NAME: game1
      HISP_DB_USERNAME: horseisle
      HISP_DB_PASSWORD: test123
      HISP_SQL_BACKEND: mariadb
    volumes:
      - /etc/hisp:/etc/hisp
    ports:
      - 12321:12321
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:latest
    container_name: hisp-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rooty
      MARIADB_DATABASE: game1
      MARIADB_USER: horseisle
      MARIADB_PASSWORD: test123
    volumes:
      - /var/lib/hisp/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  master_web:
    build: ./HorseIsleWeb/master-site
    container_name: hisp_master_web
    environment:
      HISP_WEB_DB: master
      HISP_WEB_USER: horseisle
      HISP_WEB_PASS: test123
      HISP_WEB_HOST: mariadb
      
      HISP_MAIN_FROM_EMAIL: support@horseisle.com
      HISP_MAIN_EMAIL_ACTIVATION: false
      
      HISP_WEB_HMAC: !!NOTSET!!
    ports:
      - 6969:80
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy