services:
  hispd:
    build: .
    container_name: hispd
    environment:
      - HISP_CONFIG_DIR=/etc/hisp
      - HISP_ASSETS_DIR=/usr/bin/hisp
      - HISP_LOG_FILE=stdout
    volumes:
      - /etc/hisp:/etc/hisp
    ports:
      - 12321:12321
    restart: unless-stopped