//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HISP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HISP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri 15/04/2022 
        ///.
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:19 am
        ///.
        /// </summary>
        public static string BuildTime {
            get {
                return ResourceManager.GetString("BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cross-domain-policy&gt;
        ///	&lt;allow-access-from domain=&quot;*&quot; to-ports=&quot;12321&quot; secure=&quot;false&quot;/&gt;
        ///&lt;/cross-domain-policy&gt;.
        /// </summary>
        public static string DefaultCrossDomain {
            get {
                return ResourceManager.GetString("DefaultCrossDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # =======================
        ///# Horse Isle Server Configuration    
        ///# =======================
        ///# 
        ///# Configuration Version 1.3.1
        ///# HISP was Created and Developed by SilicaAndPina
        ///# However it is NOT COPYRIGHTED! This software is in the Public Domain!
        ///#
        ///# Ip address the server will bind to (default: 0.0.0.0 ALL INTERFACES)
        ///ip=0.0.0.0
        ///
        ///# Port the server will bind to defaults: (on beta.horseisle.com: 12321, on pinto.horseisle.com: 443)
        ///# Though, 443 is likely to interfere with TLS, if you happen to have a web server [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultServerProperties {
            get {
                return ResourceManager.GetString("DefaultServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master
        ///.
        /// </summary>
        public static string GitBranch {
            get {
                return ResourceManager.GetString("GitBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03b55d148a1a109b501162095b1d04101c103cc3
        ///.
        /// </summary>
        public static string GitCommit {
            get {
                return ResourceManager.GetString("GitCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.3
        ///.
        /// </summary>
        public static string GitTag {
            get {
                return ResourceManager.GetString("GitTag", resourceCulture);
            }
        }
    }
}
