name: windows

on:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: ./HorseIsleServer

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Git Submodule update
      run: git submodule update --init --recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore
      
      
    - name: Build win-x64
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Win64.pubxml

    - name: Build win-x86
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Win32.pubxml

    - name: Build win-arm
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=WinARM.pubxml

    - name: Build win-arm64
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=WinARM64.pubxml

    - name: Upload win-x64
      uses: actions/upload-artifact@v2
      with:
        name: HISP-Win64
        path: HorseIsleServer\HISP\bin\x64\Windows\net6.0\win-x64\publish\
    
    - name: Upload win-x86
      uses: actions/upload-artifact@v2
      with:
        name: HISP-Win32
        path: HorseIsleServer\HISP\bin\x86\Windows\net6.0\win-x86\publish\
        
    - name: Upload win-arm
      uses: actions/upload-artifact@v2
      with:
        name: HISP-WinARM
        path: HorseIsleServer\HISP\bin\arm\Windows\net6.0\windows-arm\publish\

    - name: Upload win-arm64
      uses: actions/upload-artifact@v2
      with:
        name: HISP-WinARM64
        path: HorseIsleServer\HISP\bin\arm64\Windows\net6.0\windows-arm64\publish\






    - name: Upload win-x86-noobs
      uses: actions/upload-artifact@v2
      with:
        name: HISP-Win32-Noobs
        path: HorseIsleServer\N00BS\bin\x86\Windows\net6.0\win-x86\publish\


    - name: Upload win-x64-noobs
      uses: actions/upload-artifact@v2
      with:
        name: HISP-Win64-Noobs
        path: HorseIsleServer\N00BS\bin\x64\Windows\net6.0\win-x64\publish\
